[package]
name = "VoiceKek"
version = "0.1.0"
authors = ["kekonen <daniil.naumetc@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.2", features = ["postgres"] }
dotenv = "0.9.0"
telegram-bot = { path = "deps/telegram-bot/lib"}
futures = "0.1.27"
tokio-core = "0.1.17"